#Primer EJercicio clase 1 de github actions 
#name: "Hola Mundo - Deploy"

#on: 
#  push:
#    branches: ["main"]

#jobs: 
#  deploy-CF:
#    runs-on: ubuntu-latest  # Usa un entorno Linux actualizado
#    steps:
#     - uses: actions/checkout@v3  # Extrae el código del repositorio, para este ejemplo no es necesario 
#     - run: echo "Hacemos pull del codigo"
#     - run: echo "Correr migraciones"
#     - run: echo "Generar Binario"
#     - run: echo "Publicar"

    #send_notofication:
    #test_code:


#Primer EJercicio clase 1 de github actions 
#------------------------------------------------------------------------


name: deploy to server

on: push

jobs: 
  first_job:
    runs-on: ubuntu-latest

    steps: 
      - name: Hola Mundo
        run: echo "Hola Mundo"

  second_job:
    needs: first_job
    runs-on: ubuntu-latest

    steps: 
      - name: Hola Mundo
        run: echo "Hola Mundo ${{ github.ref }}"


