#Primer EJercicio clase 1 de github actions 
#name: "Hola Mundo - Deploy"

#on: 
#  push:
#    branches: ["main"]

#jobs: 
#  deploy-CF:
#    runs-on: ubuntu-latest  # Usa un entorno Linux actualizado
#    steps:
#     - uses: actions/checkout@v3  # Extrae el código del repositorio, para este ejemplo no es necesario 
#     - run: echo "Hacemos pull del codigo"
#     - run: echo "Correr migraciones"
#     - run: echo "Generar Binario"
#     - run: echo "Publicar"

    #send_notofication:
    #test_code:


#Primer EJercicio clase 1 de github actions 
#------------------------------------------------------------------------


name: deploy to server

on: push

jobs: 
  first_job:
    runs-on: ubuntu-latest

    env: 
      cf: prueba de variables

    steps: 
      - name: Hola Mundo
        run: echo "Hola Mundo - $cf"

      - name: Working dir
        id: step_1
        run: echo "my_variable=Hola Mundo" >> $GITHUB_OUTPUT

      - name: Obtener mensaje
        run: echo "${{ steps.step_1.outputs.my_variable))"

     # - name: actions
      #  uses: actions/checkout@v4
        #with: se declara para usar parametros establecidos por la accion 
          

     

  second_job:
    needs: first_job          # needs para colocar dependencias entre jobs 
    runs-on: ubuntu-latest

    steps: 
      - name: Hola Mundo
        run: echo "Hola Mundo ${{ github.ref }}"  #se declara el contexto que contiene infirmacion del proceso


